export const dummyData = [
    {
        "id": 1,
        "item_id": 2540,
        "level": 60,
        "iconId": 26017,
        "amountBought": 1,
        "price": 3180,
        "de": "Hochwald-Extrakt",
        "en": "Timber Substrate",
        "fr": "Substrat de Futaie",
        "es": "Concentrado de oquedal",
        "created_at": "2025-01-31 16:55:57"
    },
    {
        "id": 2,
        "item_id": 2540,
        "level": 60,
        "iconId": 26017,
        "amountBought": 1,
        "price": 3180,
        "de": "Hochwald-Extrakt",
        "en": "Timber Substrate",
        "fr": "Substrat de Futaie",
        "es": "Concentrado de oquedal",
        "created_at": "2025-01-31 16:55:57"
    },
    {
        "id": 3,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 52,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:55:57"
    },
    {
        "id": 4,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 52,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:55:57"
    },
    {
        "id": 5,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:55:57"
    },
    {
        "id": 6,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 7,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 8,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 9,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 10,
        "item_id": 844,
        "level": 74,
        "iconId": 105204,
        "amountBought": 1,
        "price": 429,
        "de": "Ei eines Schiefer-Dracheis",
        "en": "Slate Dreggon Egg",
        "fr": "Œuf de Dragoeuf Ardoise",
        "es": "Huevo de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 11,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 29,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 12,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 29,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 13,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 30,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 14,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 32,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 15,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 32,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 16,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 33,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 17,
        "item_id": 21271,
        "level": 70,
        "iconId": 54714,
        "amountBought": 1,
        "price": 2180,
        "de": "Draegnerys' Haare",
        "en": "Draegnerys's Hair",
        "fr": "Cheveux de Draegnerys",
        "es": "Pelo de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 18,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 11,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 19,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 12,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 20,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 12,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 21,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 13,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 22,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 13,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 23,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 13,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 24,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 44,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 25,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 44,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 26,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 44,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 27,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 45,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 28,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 29,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 30,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 700,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 31,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 772,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 32,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 773,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 33,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 774,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 34,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 35,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 36,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 37,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 38,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 46,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 39,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 48,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 40,
        "item_id": 21264,
        "level": 70,
        "iconId": 55739,
        "amountBought": 1,
        "price": 99,
        "de": "Draegnerys' Stoffstück",
        "en": "Draegnerys's Cloth",
        "fr": "Étoffe de Draegnerys",
        "es": "Tejido de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 41,
        "item_id": 21264,
        "level": 70,
        "iconId": 55739,
        "amountBought": 1,
        "price": 99,
        "de": "Draegnerys' Stoffstück",
        "en": "Draegnerys's Cloth",
        "fr": "Étoffe de Draegnerys",
        "es": "Tejido de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 42,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 1,
        "price": 14,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 43,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 1,
        "price": 14,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 44,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1199,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 45,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1199,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 46,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1200,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 47,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1200,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 48,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 49,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 50,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 53,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 51,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 54,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 52,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 55,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 53,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 55,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 54,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 55,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 55,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 1,
        "price": 55,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 56,
        "item_id": 21256,
        "level": 70,
        "iconId": 47701,
        "amountBought": 1,
        "price": 3996,
        "de": "Klaue des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Claw",
        "fr": "Griffe de Dragoeuf Albâtre",
        "es": "Garra de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 57,
        "item_id": 748,
        "level": 60,
        "iconId": 40659,
        "amountBought": 1,
        "price": 2949,
        "de": "Magnesit",
        "en": "Magnesite",
        "fr": "Magnésite",
        "es": "Magnesita",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 58,
        "item_id": 748,
        "level": 60,
        "iconId": 40659,
        "amountBought": 1,
        "price": 2949,
        "de": "Magnesit",
        "en": "Magnesite",
        "fr": "Magnésite",
        "es": "Magnesita",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 59,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 33,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 60,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 33,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 61,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 33,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 62,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 33,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 63,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 34,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 64,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 34,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 65,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 34,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 66,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 34,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 67,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 104,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 68,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 105,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 69,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 105,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 70,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 105,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 71,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2998,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 72,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2998,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 73,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 74,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 75,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 76,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 77,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 78,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 79,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 80,
        "item_id": 8367,
        "level": 120,
        "iconId": 59612,
        "amountBought": 1,
        "price": 2999,
        "de": "Crocabulia-Haut",
        "en": "Crocabulia Skin",
        "fr": "Peau de Crocabulia",
        "es": "Piel de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 81,
        "item_id": 8365,
        "level": 120,
        "iconId": 47652,
        "amountBought": 1,
        "price": 4496,
        "de": "Geborstenes Crocabulia-Horn",
        "en": "Crocabulia's Broken Horn",
        "fr": "Corne brisée de Crocabulia",
        "es": "Cuerno roto de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 82,
        "item_id": 8365,
        "level": 120,
        "iconId": 47652,
        "amountBought": 1,
        "price": 4496,
        "de": "Geborstenes Crocabulia-Horn",
        "en": "Crocabulia's Broken Horn",
        "fr": "Corne brisée de Crocabulia",
        "es": "Cuerno roto de Cocabulia",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 83,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 10,
        "price": 996,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 84,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 10,
        "price": 997,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 85,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 86,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 87,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 88,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 89,
        "item_id": 8363,
        "level": 120,
        "iconId": 47651,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachmatika",
        "en": "Dragmatic Horn",
        "fr": "Corne de Dragmatique",
        "es": "Cuerno de dragmático",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 90,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 57,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 91,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 58,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 92,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 58,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 93,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 58,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 94,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 58,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 95,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 59,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 96,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 60,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 97,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 69,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 98,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 70,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 99,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 73,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 100,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 73,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 101,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 73,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 102,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 73,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 103,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 73,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 104,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 73,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 105,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 74,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 106,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 74,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 107,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 75,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 108,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 75,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 109,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 75,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 110,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 77,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 111,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 77,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 112,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 77,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 113,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 78,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 114,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 78,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 115,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 78,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 116,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 79,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 117,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 79,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 118,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 80,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 119,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 93,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 120,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 93,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 121,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 93,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 122,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 123,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 94,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 124,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 95,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 125,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 95,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 126,
        "item_id": 8361,
        "level": 120,
        "iconId": 47650,
        "amountBought": 1,
        "price": 98,
        "de": "Horn des Drachzorn",
        "en": "Dragnnoyed Horn",
        "fr": "Corne de Dragacé",
        "es": "Cuerno de draguirritado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 127,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 10,
        "price": 184,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 128,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 1,
        "price": 14,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 129,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 1,
        "price": 14,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 130,
        "item_id": 21271,
        "level": 70,
        "iconId": 54714,
        "amountBought": 1,
        "price": 2189,
        "de": "Draegnerys' Haare",
        "en": "Draegnerys's Hair",
        "fr": "Cheveux de Draegnerys",
        "es": "Pelo de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 131,
        "item_id": 21271,
        "level": 70,
        "iconId": 54714,
        "amountBought": 1,
        "price": 2190,
        "de": "Draegnerys' Haare",
        "en": "Draegnerys's Hair",
        "fr": "Cheveux de Draegnerys",
        "es": "Pelo de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 132,
        "item_id": 21271,
        "level": 70,
        "iconId": 54714,
        "amountBought": 1,
        "price": 2191,
        "de": "Draegnerys' Haare",
        "en": "Draegnerys's Hair",
        "fr": "Cheveux de Draegnerys",
        "es": "Pelo de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 133,
        "item_id": 21271,
        "level": 70,
        "iconId": 54714,
        "amountBought": 1,
        "price": 2192,
        "de": "Draegnerys' Haare",
        "en": "Draegnerys's Hair",
        "fr": "Cheveux de Draegnerys",
        "es": "Pelo de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 134,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 10,
        "price": 539,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 135,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 10,
        "price": 320,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 136,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 38,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 137,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 39,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 138,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 10,
        "price": 97,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 139,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 18,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 140,
        "item_id": 21263,
        "level": 70,
        "iconId": 59675,
        "amountBought": 1,
        "price": 18,
        "de": "Haut des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Skin",
        "fr": "Peau de Dragoeuf Albâtre",
        "es": "Piel de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 141,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 10,
        "price": 641,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 142,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 60,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 143,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 60,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 144,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 775,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 145,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 776,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 146,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 777,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 147,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 791,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 148,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 792,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 149,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 793,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 150,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 794,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 151,
        "item_id": 846,
        "level": 74,
        "iconId": 105206,
        "amountBought": 1,
        "price": 794,
        "de": "Ei eines Kohle-Dracheis",
        "en": "Coal Dreggon Egg",
        "fr": "Œuf de Dragoeuf Charbon",
        "es": "Huevo de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 152,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 10,
        "price": 642,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 153,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 61,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 154,
        "item_id": 843,
        "level": 70,
        "iconId": 111203,
        "amountBought": 1,
        "price": 61,
        "de": "Schale eines Kohle-Dracheis",
        "en": "Coal Dreggon Shell",
        "fr": "Coquille de Dragoeuf Charbon",
        "es": "Cáscara de dragohuevo carbonoso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 155,
        "item_id": 21264,
        "level": 70,
        "iconId": 55739,
        "amountBought": 1,
        "price": 99,
        "de": "Draegnerys' Stoffstück",
        "en": "Draegnerys's Cloth",
        "fr": "Étoffe de Draegnerys",
        "es": "Tejido de Dragenerys",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 156,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 10,
        "price": 185,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 157,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 1,
        "price": 14,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 158,
        "item_id": 842,
        "level": 70,
        "iconId": 111202,
        "amountBought": 1,
        "price": 14,
        "de": "Schale eines Lehm-Dracheis",
        "en": "Clay Dreggon Shell",
        "fr": "Coquille de Dragoeuf Argile",
        "es": "Cáscara de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 159,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1243,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 160,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1243,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 161,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1243,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 162,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1244,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 163,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1268,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 164,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1268,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 165,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1268,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 166,
        "item_id": 845,
        "level": 74,
        "iconId": 105205,
        "amountBought": 1,
        "price": 1268,
        "de": "Ei eines Lehm-Dracheis",
        "en": "Clay Dreggon Egg",
        "fr": "Œuf de Dragoeuf Argile",
        "es": "Huevo de dragohuevo arcilloso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 167,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 10,
        "price": 540,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 168,
        "item_id": 1129,
        "level": 70,
        "iconId": 111211,
        "amountBought": 10,
        "price": 541,
        "de": "Schale eines Schiefer-Dracheis",
        "en": "Slate Dreggon Shell",
        "fr": "Coquille de Dragoeuf Ardoise",
        "es": "Cáscara de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 169,
        "item_id": 21256,
        "level": 70,
        "iconId": 47701,
        "amountBought": 1,
        "price": 4190,
        "de": "Klaue des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Claw",
        "fr": "Griffe de Dragoeuf Albâtre",
        "es": "Garra de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 170,
        "item_id": 21256,
        "level": 70,
        "iconId": 47701,
        "amountBought": 1,
        "price": 4190,
        "de": "Klaue des Alabaster-Dracheis",
        "en": "Alabaster Dreggon Claw",
        "fr": "Griffe de Dragoeuf Albâtre",
        "es": "Garra de dragohuevo alabastrado",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 171,
        "item_id": 748,
        "level": 60,
        "iconId": 40659,
        "amountBought": 1,
        "price": 2988,
        "de": "Magnesit",
        "en": "Magnesite",
        "fr": "Magnésite",
        "es": "Magnesita",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 172,
        "item_id": 748,
        "level": 60,
        "iconId": 40659,
        "amountBought": 1,
        "price": 2988,
        "de": "Magnesit",
        "en": "Magnesite",
        "fr": "Magnésite",
        "es": "Magnesita",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 173,
        "item_id": 748,
        "level": 60,
        "iconId": 40659,
        "amountBought": 1,
        "price": 2988,
        "de": "Magnesit",
        "en": "Magnesite",
        "fr": "Magnésite",
        "es": "Magnesita",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 174,
        "item_id": 748,
        "level": 60,
        "iconId": 40659,
        "amountBought": 1,
        "price": 2988,
        "de": "Magnesit",
        "en": "Magnesite",
        "fr": "Magnésite",
        "es": "Magnesita",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 175,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 10,
        "price": 320,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 176,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 38,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 177,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 38,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 178,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 38,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 179,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 39,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 180,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 39,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 181,
        "item_id": 308,
        "level": 70,
        "iconId": 111021,
        "amountBought": 1,
        "price": 40,
        "de": "Schale eines Kalk-Dracheis",
        "en": "Limestone Dreggon Shell",
        "fr": "Coquille de Dragoeuf Calcaire",
        "es": "Cáscara de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 182,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 110,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 183,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 111,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 184,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 111,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 185,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 112,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 186,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 112,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 187,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 113,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 188,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 114,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 189,
        "item_id": 847,
        "level": 74,
        "iconId": 105648,
        "amountBought": 1,
        "price": 114,
        "de": "Ei eines Kalk-Dracheis",
        "en": "Limestone Dreggon Egg",
        "fr": "Œuf de Dragoeuf Calcaire",
        "es": "Huevo de dragohuevo calizo",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 190,
        "item_id": 2540,
        "level": 60,
        "iconId": 26017,
        "amountBought": 1,
        "price": 3178,
        "de": "Hochwald-Extrakt",
        "en": "Timber Substrate",
        "fr": "Substrat de Futaie",
        "es": "Concentrado de oquedal",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 191,
        "item_id": 2540,
        "level": 60,
        "iconId": 26017,
        "amountBought": 1,
        "price": 3178,
        "de": "Hochwald-Extrakt",
        "en": "Timber Substrate",
        "fr": "Substrat de Futaie",
        "es": "Concentrado de oquedal",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 192,
        "item_id": 2540,
        "level": 60,
        "iconId": 26017,
        "amountBought": 1,
        "price": 3178,
        "de": "Hochwald-Extrakt",
        "en": "Timber Substrate",
        "fr": "Substrat de Futaie",
        "es": "Concentrado de oquedal",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 193,
        "item_id": 2540,
        "level": 60,
        "iconId": 26017,
        "amountBought": 1,
        "price": 3178,
        "de": "Hochwald-Extrakt",
        "en": "Timber Substrate",
        "fr": "Substrat de Futaie",
        "es": "Concentrado de oquedal",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 194,
        "item_id": 844,
        "level": 74,
        "iconId": 105204,
        "amountBought": 1,
        "price": 432,
        "de": "Ei eines Schiefer-Dracheis",
        "en": "Slate Dreggon Egg",
        "fr": "Œuf de Dragoeuf Ardoise",
        "es": "Huevo de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    },
    {
        "id": 195,
        "item_id": 844,
        "level": 74,
        "iconId": 105204,
        "amountBought": 1,
        "price": 432,
        "de": "Ei eines Schiefer-Dracheis",
        "en": "Slate Dreggon Egg",
        "fr": "Œuf de Dragoeuf Ardoise",
        "es": "Huevo de dragohuevo pizarroso",
        "created_at": "2025-01-31 16:38:57"
    }
]